# Generated by Django 4.0.1 on 2022-01-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='large_cate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='small_cate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
