# Generated by Django 4.0.1 on 2022-01-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
