# Generated by Django 4.0.1 on 2022-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_img_menu_img_url_alter_menu_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='general_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
